### PR TITLE
Properly cleanup Modal timeout

### PR DESCRIPTION
**Pull request by martimalek**
**What:**

Clean up a timeout in `Modal.tsx` 

​
**Why:**

In order to avoid state updates on unmounted components (and avoid having warnings in the terminal when running test on a component that uses the `Modal` component from Wave).

​
**How:**

- Clear the timeout to call the `onClose` callback in a `useEffect` cleanup function in `Modal.tsx` 

​
**Media:**

The warning that was appearing when testing a component that uses the `Modal`:
Screenshot 2021-11-15 at 09 26 31

**Checklist:**

-   [x] Ready to be merged

**Additional comments:**
This is a minor fix that isn't linked to an issue.

### CODE REVIEW

**Review by snapsnapturtle — APPROVED** [review]
LGTM 👍

**Comment by martimalek** [comment]
I've removed Rafael from reviewers because this is purely technical

**Comment by nlopin** [comment]
Please, rollback the package-lock because it is not related to the pr

**Review by nlopin — APPROVED** [review]

**Comment by nlopin** [comment]
@martimalek Should I merge?

**Comment by martimalek** [comment]
@nlopin Yes you can merge, do you need anything from me for that?

**Pull request merged**
