### PR TITLE
Introducing semantic/functional color variables

### PR DESCRIPTION
**Pull request by snapsnapturtle**
Hello everyone! We've been talking about semantic colors (or functional colors) for a long time already. Recently I had some time available and started implementing a first draft, which turned into this PR. Today I am introducing the basic semantic colors, the globals and specifics for the two button components `Button` and `TextButton`. See #121. 

**What**
Implemented semantic/functional color variables from the designers in the two button components `Button` and `TextButton` following the best practices picked up in other design systems like Github's Primer. In addition we are exposing the `themeGet` function to access theme variables outside of the design system components. This way we can already set a default theme and in the future have laid the groundwork for a separate "dark" theme.

**Why**
We want to be increase alignment with the design team (which is already using semantic names for colors) and developers by providing them an easy and understandable way to find the right color to use in their project when working on components, that are not part of the design system already.  We want to expose purposeful color names that represent their purpose instead of a descriptive name (like AUTHENTIC_BLUE_900). By implementing these new color names in our own components first, we will get a good understanding and have examples to share with the devs on when they can use which color.
​
**How**
In short we are adding a new variable to the theme with purpose-based names for all the colors used in the design system called `semanticColors`. This PR updates the button components to use the method to get the newly introduced colors from the `theme.ts`. After the changes, the visual result is exactly the same, but under the hood the components will not directly access the `Colors` variables anymore. In addition we are exposing the `themeGet` function that's directly accessing the `theme.js` to get the correct color from the library. It will be able to get the color from a different theme, if we add a "dark" theme in the future.

**Next Steps**
In the near future we should update our remaining components to use semantic color names and expose those via the `semanticColors` object as well. Before the the next major release, we should deprecate the Colors object in the theme.js and as an export and recommend teams to use the `themeGet` with the new semantic colors. With the next major release, we will remove the Colors object and rename `semanticColors` to just `colors` (we can probably provide a codemod, too).

Thanks as well for the alignment with design thanks to @rafael-sepeda 🚀

### CODE REVIEW

**Review by lukahartwig — APPROVED** [review]
LGTM

**Review by rafael-sepeda — CHANGES_REQUESTED** [review]
@snapsnapturtle 
I found that I made a mistake in the original JSON file that I share with you: `$background.warning` should use `$colors.brand.attentionYellow.50`
 (in the file it was 350)

**Comment by rafael-sepeda** [comment]
Question: do you think we can simplify `borderColor` to just `border`? Since other color slots do not have the “Color” pre/post-fix?

**Comment by rafael-sepeda** [comment]
@snapsnapturtle Everything looks good.
I was only not able to find the colors for the **icons of the buttons**. Or I’m missing something?

**Review by duranmla — APPROVED** [review]
Thanks for the hard work! 🚀

**Comment by snapsnapturtle** [comment]
@rafael-sepeda regarding different colors for the icons. I missed them in the first place, but now I think: Is it necessary to have a different color for the button icons?

**Comment by rafael-sepeda** [comment]
@snapsnapturtle If we have dedicated colors for text in buttons - we should have them for icons. To avoid that I can try to map text/icons to global colors (since now we have them in the new setup). I tried to do that already, but I found that because of many states its looks not very semantic/logical sometimes. If this dues not sound like a problem - we can do that. Otherwise if we think that we should have dedicated text colors - lets have them for icons (even if icon/text use the same color).

**Comment by rafael-sepeda** [comment]
@snapsnapturtle Thanks a lot for the great job and for pushing this topic forward. Really cool to finally have semantic colors live, especially in the documentation 📚. The search is really great and will help a lot!

Will it be possible for more transparency to have in the color table in addition to the hex-values the brand-color references? I mean:
- `border.primary` = `Colors.AUTHENTIC_BLUE_200`

**Comment by snapsnapturtle** [comment]
@rafael-sepeda absolutely, as long as the color matches the brand color exactly that should also be easily doable with a simple map. Can you create a new issue for this and add the documentation label? 🚀

**Pull request merged**
