### PR TITLE
ci: add semantic-release

### PR DESCRIPTION
**Pull request by lukahartwig**
This PR configures the Github Action to automatically release changes to `main` branch. It also creates an automatic changelog based on the commits in the release.

### CODE REVIEW

**Comment by nlopin** [comment]
Am i right you propose to automatically generate changelog.md? From the commit messages?

**Comment by lukahartwig** [comment]
That was my idea, yes. With this change every commit to `main` may lead to a release so updating the changelog manually seems like too much effort. Additionally he changes also get displayed in the releases tab in the repo.

The commit messages can be written while merging branches in the Github UI so we still have full control over what gets displayed there.

This is just the proposal though, I'm totally open for other approaches as well.

**Comment by lukahartwig** [comment]
`GITHUB_TOKEN` is injected automatically (except on forks), `NPM_TOKEN` was added by me under Settings > Secrets.

**Comment by nlopin** [comment]
> The commit messages can be written while merging branches in the Github UI so we still have full control over what gets displayed there.

Let's hope we won't forget about it. I tried to use automatic release notes but it backslid every time and created mess with automatic merge messages

**Review by nlopin — APPROVED** [review]

**Review by snapsnapturtle — APPROVED** [review]

**Pull request merged**
