### PR TITLE
Wech 35/bring storybook migration to main

### PR DESCRIPTION
**Pull request by martimalek**
**What:**

Bring the Storybook migration to main, this branch contains the whole Storybook migration without including the other breaking changes in #311

​
**Why:**

We want to migrate our documentation from [docz](https://www.docz.site/) to [Storybook](https://storybook.js.org/) as part of the current major.

​
**How:**

I've created this branch from [WECH-21/support-react-18](https://github.com/freenowtech/wave/tree/WECH-21/support-react-18) and rebased with `main`, getting rid of anything unrelated to the Storybook migration (React 18 migration, removing `nanoid`, using React's `useId` to generate ids).

Apart from that I've also:
- Bumped `ts-jest` to 26.5.6 in order to use Jest 26 (introduced during the Storybook migration)
- Corrected a type issue when using `Input` internal utils that depended on it's `size` prop
- Migrated compound `InfoBanner` docs to Storybook

**Checklist:**

- [x] Relevant commits from #334 have been cherry-picked to this branch
- [x] Ready to be merged

### CODE REVIEW

**Review by nlopin — COMMENTED** [review]
LGTM. I've checked out the branch, and it has started without issues.

Can you describe what was wrong with the `Input`? I see you removed the `ResponsiveValue` generic around it. I'm not sure it is correct. You can pass an array to `size` and `variant` props to make their style change based on the breakpoints.

I've assembled a [demo in Codesandbox](https://codesandbox.io/s/sad-silence-ugse0d?file=/src/App.tsx). If you make the browser tab narrower there, you'll see the change.

**Comment by martimalek** [comment]
> LGTM. I've checked out the branch, and it has started without issues.
> 
> Can you describe what was wrong with the `Input`? I see you removed the `ResponsiveValue` generic around it. I'm not sure it is correct. You can pass an array to `size` and `variant` props to make their style change based on the breakpoints.
> 
> I've assembled a [demo in Codesandbox](https://codesandbox.io/s/sad-silence-ugse0d?file=/src/App.tsx). If you make the browser tab narrower there, you'll see the change.

Hi Nik, nice catch! This was a change from a previous [commit](https://github.com/freenowtech/wave/commit/b562d9f60abe1f1a70d47d716e375a10c022c916#diff-d6d1d47b86c0d2d001d0ac3a91860769d2f355ef80b8d22297420e8f5d199094), I don't think it had any issue so I've put it back, running storybook locally it worked fine.

I've had to put back some casts of `size` in `BoxedInput` that I had removed before though

**Comment by martimalek** [comment]
I've resolved conflicts related to the recent addition of the compound `InfoBanner`, at the beginning I tried using the `Story` and `Source` APIs to have a cleaner mdx file, but I had to create a custom `Story` using [render (deprecated)](https://storybook.js.org/docs/react/api/doc-block-story#render-deprecated), which didn't correctly display the code when opening the dropdown. In the end I've added directly the code in the [mdx file](src/components/InfoBanner/docs/InfoBanner.storybook.mdx), please let me know if there's a better way to do this. 

The final docs look like:

image

**Comment by nlopin** [comment]
@martimalek do you plan to cherrypick Jan's new home page?

**Comment by martimalek** [comment]
> @martimalek do you plan to cherrypick Jan's new home page?

Hey Nik, yes, I'll try cherrypicking today/tomorrow

**Comment by martimalek** [comment]
Alright folks, I've cherry-picked the commits for the landing page
image

and changed their commit description to follow semantic commits rules
image

I think this branch has now the entire Storybook migration and should be ready for some reviews and the release 😉

**Pull request merged**
